// Regenerated on every build (see package.json's `prebuild`) so the running
// server can safely report which commit it was built from — this is what
// lets a device-comparison ("is Device A running the same build as Device
// B?") be answered by reading a value instead of guessing. Gitignored like
// any other build artifact (dist/, *.tsbuildinfo) since it's derived, not
// authored — regenerating it is what keeps it honest rather than a stale
// hand-edited string.
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

let sha = "unknown";
try {
  sha = execSync("git rev-parse --short HEAD", { cwd: join(__dirname, ".."), encoding: "utf8" }).trim();
} catch {
  // Not a git checkout (e.g. a tarball deploy with no .git) — "unknown" is
  // honest here, never a guessed/hardcoded value.
}

const dirty = (() => {
  try {
    return execSync("git status --porcelain", { cwd: join(__dirname, ".."), encoding: "utf8" }).trim().length > 0;
  } catch {
    return false;
  }
})();

writeFileSync(
  join(__dirname, "../src/version.ts"),
  `// Auto-generated by scripts/write-version.mjs at build time — do not edit.\nexport const BUILD_VERSION = ${JSON.stringify(sha + (dirty ? "-dirty" : ""))};\n`
);
console.log(`[write-version] BUILD_VERSION = ${sha}${dirty ? "-dirty" : ""}`);
