// Regenerated on every build (see package.json's `prebuild`) so the running
// server can safely report which commit it was built from — this is what
// lets a device-comparison ("is Device A running the same build as Device
// B?") be answered by reading a value instead of guessing. Gitignored like
// any other build artifact (dist/, *.tsbuildinfo) since it's derived, not
// authored — regenerating it is what keeps it honest rather than a stale
// hand-edited string.
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Prefer an explicitly-set env var over reading .git directly — confirmed
// necessary: Railway's `railway up` uploads source and rebuilds inside its
// own container, which does NOT include .git (unlike a git-triggered
// deploy, which is what Vercel's auto-populated VERCEL_GIT_COMMIT_SHA
// relies on). GIT_COMMIT_SHA is set by the deploy step itself
// (`railway variables --set GIT_COMMIT_SHA=$(git rev-parse --short HEAD)`
// immediately before `railway up`) for exactly this reason.
let sha = process.env.GIT_COMMIT_SHA || "unknown";
if (sha === "unknown") {
  try {
    sha = execSync("git rev-parse --short HEAD", { cwd: join(__dirname, ".."), encoding: "utf8" }).trim();
  } catch {
    // Neither an env var nor a usable .git checkout — "unknown" is honest
    // here, never a guessed/hardcoded value.
  }
}

// Only meaningful for a local `git rev-parse` fallback above — irrelevant
// (and unreliable without .git) once GIT_COMMIT_SHA came from an env var,
// which by construction is set from a specific commit right before deploy.
const dirty =
  !process.env.GIT_COMMIT_SHA &&
  (() => {
    try {
      return execSync("git status --porcelain", { cwd: join(__dirname, ".."), encoding: "utf8" }).trim().length > 0;
    } catch {
      return false;
    }
  })();

writeFileSync(
  join(__dirname, "../src/version.ts"),
  `// Auto-generated by scripts/write-version.mjs at build time — do not edit.\nexport const BUILD_VERSION = ${JSON.stringify(sha + (dirty ? "-dirty" : ""))};\n`
);
console.log(`[write-version] BUILD_VERSION = ${sha}${dirty ? "-dirty" : ""}`);
